name: csecom
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cloud_firestore: ^3.1.2
  equatable: ^2.0.3
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.11
  top_snackbar_flutter: ^1.0.2

dev_dependencies:
  bloc_test: ^8.5.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
